services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN=${DOMAIN}
        - UID=${UID}
        - SSL_COUNTRY=${SSL_COUNTRY}
        - SSL_STATE=${SSL_STATE}
        - SSL_LOCALITY=${SSL_LOCALITY}
        - SSL_ORGANIZATION=${SSL_ORGANIZATION}
        - SSL_ORGANIZATIONAL_UNIT=${SSL_ORGANIZATIONAL_UNIT}
    ports:
      - "443:443"
    container_name: nginx-inception
    image: nginx
  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    container_name: mariadb-inception
    image: mariadb
  wordpress:
    build:
      context: ./requirements/wordpress
      